language: go

sudo: required

notifications:
  email: false

env:
  global:
    - PROJECT_ROOT=$HOME/gopath/src/github.com/kayac/Gunfish

go:
  - 1.10.3
  - tip

addons:
  apt:
    packages:
      - curl

install:
  - cd $PROJECT_ROOT && make get-dep-on-ci && make get-deps
  - go get github.com/mitchellh/gox

script:
  - make test

before_deploy:
  - cd $PROJECT_ROOT && make packages

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - pkg/*.{zip}
  on:
    tags: true
    go: 1.10.3
