version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: |
          make test
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: |
          go get github.com/mitchellh/gox
          go get github.com/tcnksm/ghr
      - run:
          command: |
            make packages
          environment:
            CGO_ENABLED: 0
      - run: |
          make release
  docker:
    machine: true
    steps:
      - checkout
      - run: |
          export TAG=$(echo $GITHUB_REF | cut -d/ -f3)
          echo $DOCKER_TOKEN | docker login -u fujiwara --password-stdin
          cd docker
          docker build --build-arg version=$TAG -t kayac/gunfish:$TAG .
          docker push kayac/gunfish:$TAG
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
      - docker:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/
